### ISSUE TITLE
이미지 파일 동시 업로드 요청

### ISSUE THREAD

**Issue by harrydrippin** [ngEPL/ngEPL_design#1]
파일이 `.sketch` 파일로 올라와서 모바일 환경이나 Windows 환경에서 열람이 어렵습니다.
이미지 파일이 동시에 올라오면 편하지 않을까요?

**Comment by jaycho46** [comment]
일반 해상도와 고해상도 두가지 종류로 업로드 했습니다. [`6bcfa46`](https://github.com/ngEPL/ngEPL_design/commit/6bcfa46ee4e81e28695304f3a01f7a9175e8d896)
